package eu.kaluzinski.mf_importer.emums;

public enum Metric {
  AVERAGE_SPEND_BY_MONTH,
  AVERAGE_INCOME_BY_MONTH,
  AVERAGE_SAVINGS_BY_MONTH,
  COST_OF_LIVING,
  TOTAL_ACCOUNT_SPEND,
  TOTAL_ACCOUNT_SPEND_BY_MONTH,
  TOTAL_ACCOUNT_SPEND_BY_MONTH_EXCLUDING_INVESTMENTS,
  BASIC_COSTS_OF_LIVING,
  TOTAL_ACCOUNT_INCOME_BY_MONTH
}
