package eu.kaluzinski.mf_importer.emums;

public enum Metric {
  AVERAGE_SPEND_BY_MONTH,
  AVERAGE_INCOME_BY_MONTH,
  AVERAGE_SAVINGS_BY_MONTH,
  TOTAL_ACCOUNT_SPEND,
  TOTAL_ACCOUNT_SPEND_BY_MONTH;
}
